### ISSUE TITLE
implement channel for neutrino

### ISSUE THREAD

**Issue by subes** [invesdwin/invesdwin-context-integration#49]
https://github.com/hhu-bsinfo/neutrino

**Comment by subes** [comment]
Paper about its performance and why it is better than JVerbs/DISNI: https://www.researchgate.net/publication/336316741_A_Benchmark_to_Evaluate_InfiniBand_Solutions_for_Java_Applications

**Comment by subes** [comment]
can not get examples to work (neither RoCE nor iWarp):
```
20:45:10.418 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.BaseContext - Opened context for device siw0
20:45:10.418 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.BaseContext - Opened context for device siw0
20:45:10.424 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.BaseContext - Allocated protection domain
20:45:10.424 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.BaseContext - Allocated protection domain
20:45:10.434 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Allocated registered memory buffer
20:45:10.434 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Allocated registered memory buffer
20:45:10.435 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Created completion channel
20:45:10.435 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Created completion channel
20:45:10.436 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Created completion queue
20:45:10.436 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Created completion queue
20:45:10.443 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Created queue pair
20:45:10.443 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Created queue pair
20:45:10.448 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Moved queue pair into INIT state
20:45:10.448 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Moved queue pair into INIT state
20:45:10.454 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Local connection information: ConnectionInformation[portNumber=1, localId=0, queuePairNumber=2]
20:45:10.454 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Local connection information: ConnectionInformation[portNumber=1, localId=0, queuePairNumber=1]
20:45:10.455 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Waiting for remote connection information
20:45:10.455 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Waiting for remote connection information
20:45:10.455 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Received connection information: ConnectionInformation[portNumber=1, localId=0, queuePairNumber=2]
20:45:10.455 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Received connection information: ConnectionInformation[portNumber=1, localId=0, queuePairNumber=1]
20:45:10.455 [Thread-0] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Moved queue pair into RTR state
20:45:10.455 [main] INFO de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext - Moved queue pair into RTR state
Exception in thread "main" Exception in thread "Thread-0" java.lang.RuntimeException: java.io.IOException: Das Argument ist ungültig
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest$1.run(RdmaTest.java:89)
Caused by: java.io.IOException: Das Argument ist ungültig
	at de.hhu.bsinfo.neutrino.verbs.QueuePair.modify(QueuePair.java:106)
	at de.hhu.bsinfo.neutrino.verbs.QueuePair.modify(QueuePair.java:111)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext.connect(ConnectionContext.java:104)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaContext.connect(RdmaContext.java:27)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest.startServer(RdmaTest.java:139)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest.call(RdmaTest.java:121)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest$1.run(RdmaTest.java:87)
java.lang.RuntimeException: java.io.IOException: Das Argument ist ungültig
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest.main(RdmaTest.java:100)
Caused by: java.io.IOException: Das Argument ist ungültig
	at de.hhu.bsinfo.neutrino.verbs.QueuePair.modify(QueuePair.java:106)
	at de.hhu.bsinfo.neutrino.verbs.QueuePair.modify(QueuePair.java:111)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.ConnectionContext.connect(ConnectionContext.java:104)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaContext.connect(RdmaContext.java:27)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest.startClient(RdmaTest.java:195)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest.call(RdmaTest.java:123)
	at de.invesdwin.context.integration.channel.sync.neutrino.examples.RdmaTest.main(RdmaTest.java:98)

```

**Comment by subes** [comment]
dropping neutrino for now because the project is archived and most likely not compatible to newest RDMA libs
